### PR TITLE
Fix:add relationship between group and permission

### PR DESCRIPTION
**Pull request by rensg001**
adding the relationship between group(role) and permission into database
[issue](https://github.com/vintasoftware/django-role-permissions/issues/86)

### CODE REVIEW

**Comment by rensg001** [comment]
@filipeximenes

**Comment by filipeximenes** [comment]
Hey @rensg001 thanks for the PR, it's been quite busy couple weeks but this is on my track to be reviewed. Sorry for the delay!

**Comment by filipeximenes** [comment]
Hey @rensg001 thanks again for your PR. Role permissions does not manages user permissions by checking `Groups`. We only handle it from the individual user perspective so we have more flexibility. If you need that I recommend making the change at your project level.

I'm closing this PR and the isse, let me know if I misunderstood something or you have a strong argument for us to start handling this.

Thanks!

**Comment by ltankey** [comment]
I've been following this and was maintaining a fork in the hope it would get merged, so am keen to ask what the rationale here is (apologies if it's the wrong spot).

Because we end up defining permissions against roles, it seemed natural to expect that a user with a role has the associated permissions. It also seemed to follow that if a role definition changes (as active development will tend to do) that users with existing permissions should receive those changes.

Are we using this wrong? Is there an intended/idiomatic way of dealing with the above scenario?

**Comment by filipeximenes** [comment]
Hey @ltankey, there's nothing essentially wrong with what you are doing and I do agree with what you said about changes. The only problem here is that, as a trade-off to gain the flexibility of having a user with a certain role but that does not have the same permissions of the role we decided to always attribute permissions directly to users and not to roles (groups). 

That said, we do have a way to 'sync' changes to roles in this library. The way to do it is via a management command. You can read more about it in the docs: http://django-role-permissions.readthedocs.io/en/stable/admin.html#management-commands

Hope this clarifies things, LMK if I missed something from your questions, happy to answer any questions :)

**Comment by filipeximenes** [comment]
I'm closing this for now, fell free to reopen in case if think there's more to be discussed

**Pull request closed without merging**
