### PR TITLE
#102 - make object checkers callable

### PR DESCRIPTION
**Pull request by finnertysea**
Fix and test case for issue #102

### CODE REVIEW

**Comment by fjsj** [comment]
Thanks for the PR @finnertysea , could you check the breaking CI? Maybe something dependency-related?

**Comment by finnertysea** [comment]
Test failed: Python 3.6, Django 3.0. It looks like there's an incompatible SQLite version being used. The following is from Travis:
```
604 File "/home/travis/build/vintasoftware/django-role-permissions/.tox/py36-djangolatest/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 65, in check_sqlite_version
605    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
606 django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.8.2).
607 ERROR: InvocationError for command /home/travis/build/vintasoftware/django-role-permissions/.tox/py36-djangolatest/bin/python manage.py test (exited with code 1)
```

**Comment by powderflask** [comment]
Any progress on this -- the CI break seems unrelated to this fix -- how can we re-run CI on this PR?

**Comment by fjsj** [comment]
I'll try to sync this with current master to re-run CI.

**Comment by fjsj** [comment]
All set, merging now @powderflask @finnertysea

**Comment by powderflask** [comment]
Thanks - this was a helpful PR that really aids unit testing object checkers.  Thanks @fjsj and @finnertysea for your work on this

**Pull request merged**
