### PR TITLE
Move tests to outside of rolepermissions directory

### PR DESCRIPTION
**Pull request by valberg**
Moving the tests outside of the package directory since there is no need to distribute them.

Also remove test_suite and tests_require fields from setup.py - they are deprecated since setuptools 41.5.0 in favor of tox. In turn remove test_requirements.txt since it is already included in tox.ini.

### CODE REVIEW

**Comment by fjsj** [comment]
Thanks, this looks great. We're having lots of Travis CI issues as well as Circle CI issues in several of our open-source repos... I just want to migrate it all to GitHub Actions. I know there's the Travis org vs. com thing, but this project simply doesn't appear in https://travis-ci.com/. That's why the tests aren't running here.

I'll run the tests manually and merge.

**Comment by valberg** [comment]
> 

Understandable :) I was also thinking about doing a github actions PR. I'll do one soon :)

**Comment by fjsj** [comment]
Cool, that would be awesome @valberg

**Comment by fjsj** [comment]
Here's a CI that uses tox and GH Actions: https://github.com/vintasoftware/entity-embed/blob/main/.github/workflows/ci.yml
It's a pytorch project, not a Django project, but swap pytorch for Django and things should be similar.
If you have other ways of making tox work well with GH Actions, please feel free to use them too. @valberg

**Pull request merged**
